Tutorial 1
JZasinets/mentoring-react pull request #1
Opened 2021-09-08 14:56 UTC by JZasinets

2021-09-09 08:57 UTC, ragozin-nikita requested changes

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/components/game.js
> +        const moves = history.map((step, move) => {
Вынеси в отдельный компонент

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/components/calculateWinner.js
> +        const [a, b, c] = lines[i];
Используй понятные имена

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/components/calculateWinner.js
> +function calculateWinner(squares) {
Используй стрелочные функции везде в приложении

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/components/board.js
> +                winner={this.props.winner && this.props.winner.includes(i)}
Используй ?. здесь

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/App.js
> +function App() {
Используй стрелочные функции

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/components/game.js
> +                    <ol>{ this.state.sortHistory ? moves : moves.reverse() }</ol>
Вынеси в отдельную функцию

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/components/square.js
> +function Square(props) {
Используй стрелочные функции (функциональный компонент с мемоизацией)

2021-09-09 08:57 UTC, ragozin-nikita commented on mentoring-react/src/components/square.js
> +            className={`square ${(props.winner) ? "square-win" : ""}` }
Деструктурируй пропсы

2021-09-09 11:54 UTC, JZasinets commented on mentoring-react/src/components/calculateWinner.js
> +        const [a, b, c] = lines[i];
Готово

2021-09-09 11:54 UTC, JZasinets commented on mentoring-react/src/components/calculateWinner.js
> +function calculateWinner(squares) {
Готово

2021-09-09 11:54 UTC, JZasinets commented on mentoring-react/src/components/board.js
> +                winner={this.props.winner && this.props.winner.includes(i)}
Готово

2021-09-09 11:54 UTC, JZasinets commented on mentoring-react/src/App.js
> +function App() {
Готово

2021-09-09 11:54 UTC, JZasinets commented on mentoring-react/src/components/game.js
> +                    <ol>{ this.state.sortHistory ? moves : moves.reverse() }</ol>
Готово

2021-09-10 07:03 UTC, ragozin-nikita requested changes

2021-09-13 08:24 UTC, merged