TodoList
JZasinets/mentoring-react pull request #3
Opened 2021-09-16 15:14 UTC by JZasinets

2021-09-17 07:42 UTC, ragozin-nikita requested changes

2021-09-17 07:42 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/addTodoItem.js
> +        return addTodoItem;
```suggestion
       addTodoItem();
```

2021-09-17 07:42 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/addTodoItem.js
> +        <form onSubmit={editTodoList()}>
```suggestion
        <form onSubmit={editTodoList}>
```

2021-09-17 07:43 UTC, ragozin-nikita requested changes

2021-09-17 07:43 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/todoList.js
> +        <Item key={item.toString()} value={item} />
```suggestion
        <Item key={String(item || "")} value={item} />
```

2021-09-23 13:05 UTC, ragozin-nikita requested changes

2021-09-23 13:05 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/listItem.js
> +                    onChange={() => store.completedTodo(item.id)}
Вынеси все стрелочные функции в переменные, чтобы они не пересоздавались на каждый клик

2021-09-23 13:05 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/store.js
> +        const newItem = ({
```suggestion
        const newItem = {
```

2021-09-23 13:05 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/store.js
> +        })
```suggestion
        }
```

2021-09-23 13:05 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/todoList.js
> +                            <button onClick={() => store.filterTodoList('all')}>All</button>
Необходимо вынести стрелочные функции

2021-09-23 14:51 UTC, JZasinets commented on mentoring-react/src/components/Todo/listItem.js
> +                    onChange={() => store.completedTodo(item.id)}
done

2021-09-23 14:51 UTC, JZasinets commented on mentoring-react/src/components/Todo/store.js
> +        if (this.filter === 'all') return this.todoItems;
done

2021-09-23 14:51 UTC, JZasinets commented on mentoring-react/src/components/Todo/store.js
> +        const newItem = ({
done

2021-09-23 14:51 UTC, JZasinets commented on mentoring-react/src/components/Todo/store.js
> +        })
done

2021-09-24 11:07 UTC, ragozin-nikita requested changes

2021-09-24 11:07 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/store.js
> +// const hydrate = create({
Unused code

2021-09-24 11:07 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/todoList.js
> +//     const filterList = useCallback((filter) => () => {
Unused code

2021-09-24 11:07 UTC, ragozin-nikita commented on mentoring-react/src/components/Todo/todoList.js
> +{/*                             <button onClick={filterList('all')}>All</button> */}
Unused code

2021-09-24 11:10 UTC, JZasinets commented on mentoring-react/src/components/Todo/todoList.js
> +//     const filterList = useCallback((filter) => () => {
Done

2021-09-24 11:10 UTC, JZasinets commented on mentoring-react/src/components/Todo/todoList.js
> +{/*                             <button onClick={filterList('all')}>All</button> */}
Done

2021-09-24 11:10 UTC, merged